# Generated by Django 5.0.14 on 2026-06-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_utilizado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('meses', models.IntegerField()),
                ('taxa_juros', models.DecimalField(decimal_places=4, max_digits=5)),
                ('valor_projetado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_simulacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
